changelog_type: release
header_prefix: "# "
version_regex: ^v?([0-9]+\.[0-9]+\.[0-9]+)$
group_config:
  - title: ğŸš€ Features
    labels:
      - feature
      - enhancement
  - title: ğŸ› Bug Fixes
    labels:
      - bug
      - fix
  - title: ğŸš§ Maintenance
    labels:
      - chore
      - maintenance
      - refactor
  - title: ğŸ“š Documentation
    labels:
      - documentation
      - docs
pull_request_title_regex: "^(?i:feature|fix|bug|chore|docs|documentation|enhancement|refactor).*"
exclude_labels:
  - skip-changelog
comment_changelog: false
include_unlabeled_changes: true
unlabeled_group_title: Other Changes
pull_request_url: false
